# production mode
version: '3.4'
services:
  front_candidat:
    image: candilib_front_candidat:${APP_VERSION:-latest}
    container_name: candilib_front_candidat
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        CYPRESS_DOWNLOAD_MIRROR: ${CYPRESS_DOWNLOAD_MIRROR}
        CLIENT_BUILD_TARGET: candidat
#    env_file:
#      - ${cnf:-.env}
    environment:
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-8000}
    ports:
      - "${FRONT_CANDIDAT_PORT:-80}:80"
    restart: always
#    networks:
#      - candilib-network
  front_admin:
    image: candilib_front_admin:${APP_VERSION:-latest}
    container_name: candilib_front_admin
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        CYPRESS_DOWNLOAD_MIRROR: ${CYPRESS_DOWNLOAD_MIRROR}
        CLIENT_BUILD_TARGET: admin
#    env_file:
#      - ${cnf:-.env}
    environment:
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-8000}
    ports:
      - "${FRONT_ADMIN_PORT:-80}:80"
    restart: always
#    networks:
#      - candilib-network

#networks:
#  candilib-network:
#    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: 1450
networks:
  default:
    external:
      name: ${APP}-network
