# production mode
version: '3.5'
services:
  scheduler:
    image: candilib_scheduler:${APP_VERSION:-latest}
    container_name: candilib_scheduler
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        NPM_AUDIT_DRY_RUN: ${NPM_AUDIT_DRY_RUN}
        APP_VERSION: ${APP_VERSION}
#    ports:
#      - "${SCHEDULER_PORT:-8040}:8040"
#    env_file:
#      - ${cnf:-.env}
    environment:
      NODE_ENV: production
      SCHEDULER_NAME: ${SCHEDULER_NAME}
      MONGO_URL: ${MONGO_URL:-mongodb://adminCandilib:changeme78@db:27017/candilib}
      API_BASE_URL: ${API_BASE_URL:-http://api:8000}
      API_PREFIX: ${API_PREFIX:-/api/v2}
      DISABLE_SCHEDULE: ${DISABLE_SCHEDULE}
      DISABLE_DEFINE: ${DISABLE_DEFINE}
      JOBS_LIST: ${JOBS_LIST}

networks:
  default:
    external:
      name: ${APP}-network
