# development mode
version: '3.5'
services:
  nginx_candidat:
    image: nginx
    container_name: api_nginx_candidat
    volumes:
      # - ../client/nginx/nginx.template:/etc/nginx/nginx.template
      - ./nginx/nginx.template:/etc/nginx/nginx.template
      - ../client/nginx/run.sh:/run.sh
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
    environment:
      API_HOST: ${API_HOST:-candilib_api}
      API_PORT: ${API_PORT:-8000}
      LINE_DELAY: ${LINE_DELAY}
      APP_USER_LIMIT_RATE: ${APP_USER_LIMIT_RATE}
      APP_USER_BURST: ${APP_USER_BURST}
      API_USER_SCOPE: ${API_USER_SCOPE}
      API_USER_ID_LIMIT_RATE: ${API_USER_ID_LIMIT_RATE}
      API_USER_ID_BURST: ${API_USER_ID_BURST}
      API_USER_GET_LIMIT_RATE: ${API_USER_GET_LIMIT_RATE}
      API_USER_GET_BURST: ${API_USER_GET_BURST}
      API_USER_POST_LIMIT_RATE: ${API_USER_POST_LIMIT_RATE}
      API_USER_POST_BURST: ${API_USER_POST_BURST}
      API_USER_PATCH_LIMIT_RATE: ${API_USER_PATCH_LIMIT_RATE}
      API_USER_PATCH_BURST: ${API_USER_PATCH_BURST}
      API_USER_PUT_LIMIT_RATE: ${API_USER_PUT_LIMIT_RATE}
      API_USER_PUT_BURST: ${API_USER_PUT_BURST}
      API_USER_HEAD_LIMIT_RATE: ${API_USER_HEAD_LIMIT_RATE}
      API_USER_HEAD_BURST: ${API_USER_HEAD_BURST}
      API_USER_DELETE_LIMIT_RATE: ${API_USER_DELETE_LIMIT_RATE}
      API_USER_DELETE_BURST: ${API_USER_DELETE_BURST}
      API_USER_OPTIONS_LIMIT_RATE: ${API_USER_OPTIONS_LIMIT_RATE}
      API_USER_OPTIONS_BURST: ${API_USER_OPTIONS_BURST}
      PUBLIC_PATH: /candilib
    ports:
      - "${WEB_PORT:-8000}:80"
      - "80:80"
    depends_on:
      - api
    networks:
      - candilib-network
    entrypoint: ["/run.sh"]

networks:
  candilib-network:
    name: candilib-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
  notused:
